### PR TITLE
thread-safety, asynchronous input, track past events

### PR DESCRIPTION
**Pull request by frapex**
I have been working on a reimplementation of logstash-filter-throttle to suit the needs of my customer. The plugin is now thread-safe, supports asynchronous input and properly tracks past events.

Refer to issue https://github.com/logstash-plugins/logstash-filter-throttle/issues/4 for more information.

### CODE REVIEW

**Comment by ghost** [comment]
Jenkins standing by to test this. If you aren't a maintainer, you can ignore this comment. Someone with commit access, please review this and clear it for Jenkins to run; then  say 'jenkins, test it'.

**Comment by Hikariii** [comment]
+1 for re-checking this PR and ensure thread-safety

**Comment by frapex** [comment]
It has been over two months, any updates?

**Comment by cschotke** [comment]
+1

**Comment by timbunce** [comment]
Any news on this? It's been over seven months now.
This is the only plugin preventing us from using multiple worker threads.

**Comment by timbunce** [comment]
@frapex, any chance you could update the PR to merge cleanly with the current master?

**Comment by suyograo** [comment]
@frapex Thanks! Can you also add some tests to cover the new changes?

**Comment by frapex** [comment]
@timbunce, I updated the PR. There was one merge conflict. I dropped the changes from upstream; the PR re-implements the entire plugin.

**Comment by frapex** [comment]
@suyograo, I won't be able to add tests any time soon due to lack of time.

It would be great if someone else can add some tests. Ofcourse, I tested the plugin while I was working on it. But testing focused on thread-safety: multiple input streams, multiple workers and getting the expected/correct output.

**Comment by frapex** [comment]
@suyograo, the build fails, and I am not sure why (or how to fix it). Can you take a look?

**Comment by suyograo** [comment]
@frapex this failure just got fixed and we'll be publishing a new snapshot version to fix it here.. Ref #https://github.com/elastic/logstash/issues/5361

**Comment by timbunce** [comment]
Much as I'd love to see more tests, please don't hold up integrating this just for lack of _new_ tests.

**Comment by suyograo** [comment]
@frapex restarted the tests, now we get this: 

```
NameError: uninitialized constant ThreadSafe
    const_missing at org/jruby/RubyModule.java:2719
           (root) at /home/travis/build/logstash-plugins/logstash-filter-throttle/lib/logstash/filters/throttle.rb:144
          require at org/jruby/RubyKernel.java:1040
          require at /home/travis/build/logstash-plugins/logstash-filter-throttle/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65
           (root) at /home/travis/build/logstash-plugins/logstash-filter-throttle/spec/filters/throttle_spec.rb:1
             load at org/jruby/RubyKernel.java:1059
           (root) at /home/travis/build/logstash-plugins/logstash-filter-throttle/spec/filters/throttle_spec.rb:2
             each at org/jruby/RubyArray.java:1613
           (root) at /home/travis/build/logstash-plugins/logstash-filter-throttle/vendor/bundle/jruby/1.9/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1
  load_spec_files at /home/travis/build/logstash-plugins/logstash-filter-throttle/vendor/bundle/jruby/1.9/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361
  load_spec_files at /home/travis/build/logstash-plugins/logstash-filter-throttle/vendor/bundle/jruby/1.9/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359
            setup at /home/travis/build/logstash-plugins/logstash-filter-throttle/vendor/bundle/jruby/1.9/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106
              run at /home/travis/build/logstash-plugins/logstash-filter-throttle/vendor/bundle/jruby/1.9/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92
              run at /home/travis/build/logstash-plugins/logstash-filter-throttle/vendor/bundle/jruby/1.9/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78
             load at org/jruby/RubyKernel.java:1059
           (root) at /home/travis/build/logstash-plugins/logstash-filter-throttle/vendor/bundle/jruby/1.9/bin/rspec:23
```

**Comment by frapex** [comment]
@suyograo, I added the runtime dependency "thread_safe" to logstash-filter-throttle.gemspec. Moved requires out of register(). Added runtime dependency for "atomic". Now only the actual tests fail.

**Comment by frapex** [comment]
@suyograo all tests pass, please merge

**Comment by AGirin** [comment]
We are getting this error if we try to use frapex's updates (Logstash 2.3.3):

{:timestamp=>"2016-06-21T18:03:01.228000-0500", :message=>"Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash.", "exception"=>#<NoMethodError: undefined method `update' for nil:NilClass>, "backtrace"=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-throttle-2.0.4/lib/logstash/filters/throttle.rb:243:in `filter'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java/lib/logstash/filters/base.rb:151:in`multi_filter'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java/lib/logstash/filters/base.rb:148:in`multi_filter'", "(eval):240017:in `initialize'", "org/jruby/RubyArray.java:1613:in`each'", "(eval):240010:in `initialize'", "org/jruby/RubyProc.java:281:in`call'", "(eval):15415:in `filter_func'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java/lib/logstash/pipeline.rb:267:in`filter_batch'", "org/jruby/RubyArray.java:1613:in `each'", "org/jruby/RubyEnumerable.java:852:in`inject'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java/lib/logstash/pipeline.rb:265:in `filter_batch'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java/lib/logstash/pipeline.rb:223:in`worker_loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java/lib/logstash/pipeline.rb:201:in `start_workers'"], :level=>:error}

Not sure what this means. Just wanted to report.

**Comment by AGirin** [comment]
We are using Logstash 2.3.4 and occasionally see this in the logs:

```
{:timestamp=>"2016-07-28T11:34:34.318000-0500", :message=>"Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash.", "exception"=>#<NoMethodError: undefined method `latest=' for nil:NilClass>....
```

We are using @frapex code in throttle and it looks to be working fine most of the time. Any ideas on why this is happening?

This happens under very heavy load and a lot of throttling.

**Comment by frapex** [comment]
@AGirin Can you please create a new issue for the exception? Then I'll look into it next week.

**Comment by frapex** [comment]
@suyograo @untergeek Any chance to get this merged? Pull request has been open since September 2015. My customer has a support contract with Elastic, does that help?

**Comment by untergeek** [comment]
@frapex I apologize for the lack of response.  We dropped the ball here, and that's not okay.  

You've provided tests here, and that's wonderful.  But before we can merge, it needs to be rebased first.  Can you do that please?  Also, while you're at it, can you increment the minor version number, and add a blurb to the changelog?

**Comment by frapex** [comment]
@untergeek done

**Comment by untergeek** [comment]
LGTM™, @frapex 

With your changes, do you think it makes more sense to bump the major version, instead of just a minor version bump?

**Comment by frapex** [comment]
@untergeek Yes I believe that makes sense. Is it okay to amend the last commit with a major version bump?

**Comment by untergeek** [comment]
Please do!

**Comment by frapex** [comment]
@untergeek go for it :)

**Comment by untergeek** [comment]
Thanks for your prolonged patience, @frapex

**Comment by timbunce** [comment]
Many thanks @frapex, @untergeek and co!

**Comment by mohamadkhan19** [comment]
@AGirin Hi. I have recently started writing logstash plugins. By seeing the error all I can say that there is some error at line 243 in thorttle.rb file. I am facing the same error in one of my in-progress plugins. In my code its with respect to a line which involves "event[fieldname]". I haven't solve my error yet. If I have anything surely I try to help 

In response to the following reply.
`We are getting this error if we try to use frapex's updates (Logstash 2.3.3):

{:timestamp=>"2016-06-21T18:03:01.228000-0500", :message=>"Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash.", "exception"=>#, "backtrace"=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-throttle-2.0.4/lib/logstash/filters/**_throttle.rb:243:in_** filter'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java/lib/logstash/filters/base.rb:151:inmulti_filter'", "org/jruby/RubyArray.java:1613:in each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java/lib/logstash/filters/base.rb:148:inmulti_filter'", "(eval):240017:in initialize'", "org/jruby/RubyArray.java:1613:ineach'", "(eval):240010:in initialize'", "org/jruby/RubyProc.java:281:incall'", "(eval):15415:in filter_func'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java/lib/logstash/pipeline.rb:267:infilter_batch'", "org/jruby/RubyArray.java:1613:in each'", "org/jruby/RubyEnumerable.java:852:ininject'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java/lib/logstash/pipeline.rb:265:in filter_batch'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java/lib/logstash/pipeline.rb:223:inworker_loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java/lib/logstash/pipeline.rb:201:in `start_workers'"], :level=>:error}

Not sure what this means. Just wanted to report. `

**Pull request merged**
