### PR TITLE
make throttle threadsafe

### PR DESCRIPTION
**Pull request by addisonj**
This is from elasticsearch/logstash#1469

It makes throttle theadsafe

### CODE REVIEW

**Comment by IngaFeick** [comment]
+1 Strongly needed :)

**Comment by mre** [comment]
+1

**Comment by xo4n** [comment]
+1

**Comment by markwalkom** [comment]
@suyograo can someone check this out please?

**Comment by mrwillihog** [comment]
Hi @addisonj. I've run this in production but unfortunately I ran into an issue. I'll try and explain below.

For the purpose of this test, lets assume this is my config:

``` ruby
throttle {
  before_count => 0
  after_count => 10
  period => 60
  key => "%{UUID}"
  max_counters => 100000
}
```

I then ran a load test of around 500 req/s. This should result in ~30,000 UUIDs per 60 seconds. However, when I run this patch, after 100,000 requests it starts spewing log messages like:

``` ruby
{
  :timestamp=>"2015-08-31T11:19:16.913000+0000", 
  :message=>"filters/LogStash::Filters::Throttle: Purging oldest counter because max_counters exceeded. Use a better key to prevent too many unique event counters.", 
  :key=>"43b4dd82-4fd0-11e5-8b98-02fc3a693d29", 
  :expiration=>2015-08-31 11:15:21 +0000, 
  :level=>:warn
}
```

Using the original version of this filter I don't receive a single warning of this kind.

I think the keys aren't being expired after 60 seconds with this version, which means eventually you start churning keys. What I think should happen is that after 60 seconds old keys are removed so as long as I'm not running > 100,000 req per minute I should never see that warning.

Hope that makes sense.

Just to add - this became an issue because all worker threads were maxing out their CPUs - potentially because of all the logging they were doing.

**Comment by ghost** [comment]
Jenkins standing by to test this. If you aren't a maintainer, you can ignore this comment. Someone with commit access, please review this and clear it for Jenkins to run; then  say 'jenkins, test it'.

**Comment by Hikariii** [comment]
+1

**Comment by cschotke** [comment]
+1

**Comment by addisonj** [comment]
I am not using logstash anymore these days, so its pretty low priority for me to dig in and get this fixed, but looking at the code (its been a loooong time), I could see a few places where it might be. Ideally, if someone wants to take this over that would be great, otherwise, if someone just wants to test a few changes for me, that would make it much easier to get this working.

**Comment by timbunce** [comment]
This PR appears to be superseded by #5. Can someone confirm?

**Comment by frapex** [comment]
@timbunce comfirmed. logstash-filter-throttle is multithreaded since v4.0.0. This pull request is superseded by https://github.com/logstash-plugins/logstash-filter-throttle/pull/5) and can be closed.

**Comment by frapex** [comment]
@addisonj your pull request has been superseded by https://github.com/logstash-plugins/logstash-filter-throttle/pull/5. Can you close the pull request?

**Pull request closed without merging**
